name: warshati
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0
  flutter_bloc: ^8.1.3
  dio: ^5.3.4
  get_it: ^8.0.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  go_router: ^14.4.1
  analyzer: ^6.2.0
  pretty_dio_logger: ^1.3.1
  permission_handler: ^11.1.0
  colorize: ^3.0.0
  easy_localization: ^3.0.6
  url_launcher_windows: ^3.1.1
  url_launcher: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_dotenv: ^5.1.0
  bot_toast: ^4.1.3
  connectivity_plus: ^6.0.3
  retrofit: ^4.1.0
  injectable: ^2.1.6
  intl: ^0.19.0
  path_provider: ^2.1.5
  flutter_svg: ^2.0.14
  lottie: ^3.1.3
  cached_network_image: ^3.4.1
  flutter_secure_storage: ^9.2.2
  flutter_native_splash: ^2.4.4
  gif: ^2.3.0
  queen_validators: ^1.0.1
  carousel_slider: ^5.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
 
 
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  dependency_validator: ^4.1.1
  build_runner: ^2.4.9
  hive_generator: ^2.0.1
  retrofit_generator: ^9.1.4
  injectable_generator: ^2.1.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/i18n/
    - assets/lottie/
    #.Env file
    - .env


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
